### PR TITLE
Feature/fb universal tile templates

### PR DESCRIPTION
**Pull request by dahby**
Changes in this pull request include:

- Folder structure for Universal Templates based on channel
- Templates for Facebook messenger interactions
- Expanded READMEs for each channel folder

### CODE REVIEW

**Review by JasonSowers — CHANGES_REQUESTED** [review]
It would be helpful to in some place have a link to the [facebook documentation](https://developers.facebook.com/docs/messenger-platform/reference/templates/generic) so that developers can see the limitations the are coming from facebook.

**Review by cshape — APPROVED** [review]
Looks good to me, although I haven't tested the JSON myself on Facebook. I trust you've got it right and we can always adjust if we see anything needs tweaking.

Appreciate the info on the channel limitations like min/max elements.

**Comment by cshape** [comment]
@JasonSowers I think you've got to merge this as your change request blocks merging. You've got my go-ahead in any case.

**Review by JasonSowers — CHANGES_REQUESTED** [review]
small nit pick, but if we are not capitalizing the LP developer documentation link, I don't think we should capitalize the facebook stoff, either way they should match.  this is for all the changes

**Review by JasonSowers — APPROVED** [review]

**Pull request merged**
